### ISSUE TITLE
现在logstash 现在有提供java版了

### ISSUE THREAD

**Issue by kikiyou** [DTStack/jlogstash#1]
logstash 官方从5.x 开始 提供将java版本

比如：
Logstash 5.0.0-beta1
https://artifacts.elastic.co/downloads/logstash/logstash-5.0.0-beta1.zip

**Comment by yangsishu** [comment]
什么时候出来，到时候可以对比下

**Comment by yangsishu** [comment]
官方这个版本还是基于jruby，只是加了logstas-core-event 这个java版本，之前就可以用ruby调用java的形式，我以为是直接就是纯java 的应用，本生ruby调用java 的形式会存在数据结构的转化性能跟原生java还是有差距的
