### ISSUE TITLE
为什么https://oss.sonatype.org/上面下载的jar包用不了呢

### ISSUE THREAD

**Issue by guomm** [DTStack/jlogstash#11]
jlogstash-1.0.0-with-dependencies.jar 核心代码放在jlogstash/lib/下

**Comment by yangsishu** [comment]
能把报错的信息发下吗

**Comment by guomm** [comment]
input.file-1.0.0-with-dependencies.jar 放在jlogstash/plugin/input下 
output.file-1.0.0-with-dependencies.jar 放在jlogstash/plugin/output下
运行报错呢
  1 inputs:
  2     - File:
  3         path: /usr/local/nginx/logs/es_access.20170814.log
  4         startPosition: "beginning"
  5 
  6 
  7 outputs:
  8     - File:
  9         path: /usr/local/nginx/logs/jlogstash.log
 10         timezone: Asia/Shanghai
我配置文件

**Comment by guomm** [comment]
报错信息：
214 2017-08-25 21:27:33.927 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:71] - filter works:36
215 2017-08-25 21:27:33.938 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:71] - filter works:36
216 2017-08-25 21:27:33.940 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:55] - input queue coefficient:0.19531
217 2017-08-25 21:27:33.941 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:88] - input queue size:59
218 2017-08-25 21:27:33.946 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:79] - output works:24
219 2017-08-25 21:27:33.946 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:79] - output works:24
220 2017-08-25 21:27:33.947 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:63] - output queue coefficient:0.48828
221 2017-08-25 21:27:33.947 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:107] - output queue size:146
222 2017-08-25 21:27:33.964 [main] WARN  com.dtstack.jlogstash.classloader.JarClassLoader [JarClassLoader.java:72] - userDir:/usr/local/jlogstash-4.1.0
223 2017-08-25 21:27:33.966 [main] WARN  com.dtstack.jlogstash.classloader.JarClassLoader [JarClassLoader.java:96] - getClassLoadJarUrls:{input:input.file=[Ljava.net.URL;@1abe675c, output:output.file=[Ljava.net.URL;@4a73d6bb}
224 2017-08-25 21:27:33.968 [main] ERROR com.dtstack.jlogstash.Main [Main.java:53] - jlogstash start error:null
225 com.dtstack.jlogstash.classloader.JarClassLoader.getClassLoaderByPluginName(62)
226 com.dtstack.jlogstash.factory.InstanceFactory.getPluginClass(114)
227 com.dtstack.jlogstash.factory.InputFactory.getBatchInstance(64)
228 com.dtstack.jlogstash.assembly.AssemblyPipeline.assemblyPipeline(73)
229 com.dtstack.jlogstash.Main.main(51)

**Comment by yangsishu** [comment]
input.file-1.0.0-with-dependencies.jar  把这个改成file-1.0.0-with-dependencies.jar 
output.file-1.0.0-with-dependencies.jar 改成 file-1.0.0-with-dependencies.jar

**Comment by yangsishu** [comment]
就是把input 和output 前缀去掉试下

**Comment by guomm** [comment]
嗯嗯，我试试

**Comment by guomm** [comment]
又报其他的错了
231 2017-08-25 21:38:01.900 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:71] - filter works:36
232 2017-08-25 21:38:01.908 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:71] - filter works:36
233 2017-08-25 21:38:01.909 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:55] - input queue coefficient:0.19531
234 2017-08-25 21:38:01.910 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:88] - input queue size:59
235 2017-08-25 21:38:01.913 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:79] - output works:24
236 2017-08-25 21:38:01.914 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:79] - output works:24
237 2017-08-25 21:38:01.914 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:63] - output queue coefficient:0.48828
238 2017-08-25 21:38:01.914 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:107] - output queue size:146
239 2017-08-25 21:38:01.930 [main] WARN  com.dtstack.jlogstash.classloader.JarClassLoader [JarClassLoader.java:72] - userDir:/usr/local/jlogstash-4.1.0
240 2017-08-25 21:38:01.932 [main] WARN  com.dtstack.jlogstash.classloader.JarClassLoader [JarClassLoader.java:96] - getClassLoadJarUrls:{input:file=[Ljava.net.URL;@49cd21c7, output:file=[Ljava.net.URL;@3a64b5ab}
241 2017-08-25 21:38:01.956 [main] WARN  com.dtstack.jlogstash.factory.InstanceFactory [InstanceFactory.java:63] - field: path annotation:Required check
242 2017-08-25 21:38:01.958 [main] ERROR com.dtstack.jlogstash.Main [Main.java:53] - jlogstash start error:Can not set static java.util.List field com.dtstack.jlogstash.inputs.File.path to java.lang.String
243 sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(164)
244 sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(168)
245 sun.reflect.UnsafeStaticObjectFieldAccessorImpl.set(79)
246 java.lang.reflect.Field.set(680)
247 com.dtstack.jlogstash.factory.InstanceFactory.configInstance(71)
248 com.dtstack.jlogstash.factory.InputFactory.getInstance(45)
249 com.dtstack.jlogstash.factory.InputFactory.getBatchInstance(65)
250 com.dtstack.jlogstash.assembly.AssemblyPipeline.assemblyPipeline(73)
251 com.dtstack.jlogstash.Main.main(51)

**Comment by yangsishu** [comment]
path 属性是个list 不是String类型

**Comment by yangsishu** [comment]
["/yangsishu/user/ll","/hhhh/hhh"]

**Comment by guomm** [comment]
要修改源代码自己编译吗？

**Comment by guomm** [comment]
25 outputs:
 26     - File:
 27         path: /Users/sishuyss/ysq_%{tenant_id}_%{+YYYY.MM.dd}.txt
 28         timezone: Asia/Shanghai
 29     - Performance:
 30         path: /Users/sishuyss/performance.txt

**Comment by guomm** [comment]
我按照example.yml里面配置的
 25 outputs:
 26     - File:
 27         path: /Users/sishuyss/ysq_%{tenant_id}_%{+YYYY.MM.dd}.txt
 28         timezone: Asia/Shanghai
 29     - Performance:
 30         path: /Users/sishuyss/performance.txt

**Comment by yangsishu** [comment]
那这个配置比较老了，没更新

**Comment by yangsishu** [comment]
你这边最好把源码下载下来自己编译

**Comment by yangsishu** [comment]
插进的属性说明最好看文档

**Comment by guomm** [comment]
能给一个最新配置的例子吗？https://github.com/DTStack/jlogstash-input-plugin/blob/master/README.md 这里面讲的也不是很详细，说path的参数类型是列表，但我不知道在你们配置文件中，列表是如何表示的

**Comment by yangsishu** [comment]
json 格式的 ["/home/admin"]

**Comment by yangsishu** [comment]
path: ["/usr/local/nginx/logs/es_access.20170814.log"]

**Comment by guomm** [comment]
。。。又报错了
2017-08-25 21:45:44.374 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:71] - filter works:36
254 2017-08-25 21:45:44.382 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:71] - filter works:36
255 2017-08-25 21:45:44.384 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:55] - input queue coefficient:0.19531
256 2017-08-25 21:45:44.384 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:88] - input queue size:59
257 2017-08-25 21:45:44.388 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:79] - output works:24
258 2017-08-25 21:45:44.388 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:79] - output works:24
259 2017-08-25 21:45:44.388 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:63] - output queue coefficient:0.48828
260 2017-08-25 21:45:44.388 [main] WARN  com.dtstack.jlogstash.assembly.CmdLineParams [CmdLineParams.java:107] - output queue size:146
261 2017-08-25 21:45:44.402 [main] WARN  com.dtstack.jlogstash.classloader.JarClassLoader [JarClassLoader.java:72] - userDir:/usr/local/jlogstash-4.1.0
262 2017-08-25 21:45:44.404 [main] WARN  com.dtstack.jlogstash.classloader.JarClassLoader [JarClassLoader.java:96] - getClassLoadJarUrls:{input:file=[Ljava.net.URL;@53011788, output:file=[Ljava.net.URL;@6cb00c4a}
263 2017-08-25 21:45:44.429 [main] WARN  com.dtstack.jlogstash.factory.InstanceFactory [InstanceFactory.java:63] - field: path annotation:Required check
264 2017-08-25 21:45:44.436 [pool-4-thread-3] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:0.
265 2017-08-25 21:45:44.437 [pool-4-thread-4] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:1.
266 2017-08-25 21:45:44.437 [pool-4-thread-5] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:2.
267 2017-08-25 21:45:44.437 [pool-4-thread-6] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:3.
268 2017-08-25 21:45:44.437 [pool-4-thread-7] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:4.
269 2017-08-25 21:45:44.438 [pool-4-thread-9] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:6.
270 2017-08-25 21:45:44.438 [pool-4-thread-10] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:7.
271 2017-08-25 21:45:44.438 [pool-4-thread-11] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:8.
272 2017-08-25 21:45:44.439 [pool-4-thread-12] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:9.
273 2017-08-25 21:45:44.439 [pool-4-thread-13] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:10.
274 2017-08-25 21:45:44.439 [pool-4-thread-14] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:11.
275 2017-08-25 21:45:44.439 [pool-4-thread-15] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:12.
276 2017-08-25 21:45:44.440 [pool-4-thread-16] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:13.
277 2017-08-25 21:45:44.440 [pool-4-thread-17] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:14.
278 2017-08-25 21:45:44.440 [pool-4-thread-18] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:15.
279 2017-08-25 21:45:44.441 [pool-4-thread-19] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:16.
280 2017-08-25 21:45:44.441 [pool-4-thread-20] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:17.
281 2017-08-25 21:45:44.450 [pool-4-thread-21] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:18.
282 2017-08-25 21:45:44.450 [pool-4-thread-22] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:19.
283 2017-08-25 21:45:44.450 [pool-4-thread-23] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:20.
284 2017-08-25 21:45:44.451 [pool-4-thread-24] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:21.
285 2017-08-25 21:45:44.451 [pool-4-thread-25] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:22.
286 2017-08-25 21:45:44.451 [pool-4-thread-26] WARN  com.dtstack.jlogstash.inputs.File [File.java:470] - invalid FileRunnable thread, threadReadFileMap don't init needReadList of this index:23.
287 2017-08-25 21:45:44.456 [main] WARN  com.dtstack.jlogstash.factory.InstanceFactory [InstanceFactory.java:63] - field: path annotation:Required check
288 2017-08-25 21:45:44.605 [main] ERROR com.dtstack.jlogstash.Main [Main.java:53] - jlogstash start error:Can not set static java.lang.String field com.dtstack.jlogstash.outputs.File.path to java.util.ArrayList
289 sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(164)
290 sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(168)
291 sun.reflect.UnsafeStaticObjectFieldAccessorImpl.set(79)
292 java.lang.reflect.Field.set(680)
293 com.dtstack.jlogstash.factory.InstanceFactory.configInstance(71)
294 com.dtstack.jlogstash.factory.OutputFactory.getInstance(46)
295 com.dtstack.jlogstash.factory.OutputFactory.getBatchInstance(72)
296 com.dtstack.jlogstash.assembly.pthread.OutputThread.initOutPutThread(63)
297 com.dtstack.jlogstash.assembly.AssemblyPipeline.assemblyPipeline(76)
298 com.dtstack.jlogstash.Main.main(51)


我配置文件：

  1 inputs:
  2     - File:
  3         path: ["/usr/local/nginx/logs/es_access.20170814.log"]
  4         startPosition: "beginning"
  5 
  6 
  7 outputs:
  8     - File:
  9         path: ["/usr/local/nginx/logs/jlogstash.log"]
 10         timezone: Asia/Shanghai

**Comment by yangsishu** [comment]
output 插件的path 是string

**Comment by guomm** [comment]
可以了哈

**Comment by guomm** [comment]
谢谢~
