### ISSUE TITLE
是否可以上传下TestInputPlugin类的emit prepare和release方法 

### ISSUE THREAD

**Issue by springCkWyy** [DTStack/jlogstash#12]
是否可以上传下TestInputPlugin类的emit prepare和release方法   还不知道下面具体的逻辑  还有fliter和 output  或者可以给下思路 该如何继续下去  谢谢哈

**Comment by yangsishu** [comment]
这个是每个插件实现的内容都不一样的，jlogstash只提供接口规范。你可以看下去现在jlogstash-input-plugin， jlogstash-fliter-plugin ，jlogstash-output-plugin 这些插件工程里面的插件的代码。
