### ISSUE TITLE
filters config example 

### ISSUE THREAD

**Issue by walterxue** [DTStack/jlogstash#16]
看了說明還是不太明白怎麼去設置filters 
可以請大神幫忙一下嗎??

已下是我用官方的logstsh 設置的設定檔
input {
  beats {
    port => 5044
    client_inactivity_timeout => 300
  }
}

filter{

  if "beats_input_codec_plain_applied" in [tags] {
        mutate {
            remove_tag => ["beats_input_codec_plain_applied"]
        }
    }
  if "_geoip_lookup_failure" in [tags] {
                drop { }
        }

  if "_grokparsefailure" in [tags] {
            drop { }
  }
  if [xclientip] == "-" {
      mutate{
                replace => { "xclientip" => "0.0.0.0" }
            }
        }
  if [type] in [ "aa", "bb", "cc" ] {

  grok{
      patterns_dir => ["/usr/local/logstash/patterns"]
      match => [ "message", "%{COMBINEDAPACHELOG2}" ]
    }
  geoip{
        source => "xclientip"
        target => "geoip"
        database => "/usr/local/logstash/GeoIP/GeoLite2-City.mmdb"
        add_field => [ "[geoip][coordinates]", "%{[geoip][longitude]}" ]
        add_field => [ "[geoip][coordinates]", "%{[geoip][latitude]}"  ]
   }
        mutate{
        convert => [ "[geoip][coordinates]", "float", "bytes", "integer", "elapsedmillis", "integer" ]
        }
   date {
        match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" , "ISO8601" ]
        target => "@timestamp"

   }

}
}

output {
if [type] in [ "aa", "bb", "cc" ] {
  elasticsearch {
    hosts =>[ "192.168.1.111:9200","192.168.1.110:9200" ]
    index => "%{type}-%{[@metadata][beat]}-%{+YYYY.MM.dd}"
#    flush_size => 50000
    timeout => "60"
    document_type => "%{[@metadata][type]}"
    template => "/usr/local/logstash/filebeat-index-template.json"
    template_overwrite => true
    user => 'elastic'
    password => 'changeme'
  }
}
}

**Comment by yangsishu** [comment]
你这是logstash 的配置，jlogstash 配置跟这个有些不一样的，你可以说下具体哪个插件不知道，我可以跟你说下

**Comment by walterxue** [comment]
目前主要是使用grok 插件~~

**Comment by yangsishu** [comment]
jgrok src属性 是你要解析的字段，pattern 属性是如果你要自定义正则表达式，就需要填

**Comment by yangsishu** [comment]
这个插件还有bug 还没处理

**Comment by yangsishu** [comment]
其他开发者发现的bug ，还没处理

https://github.com/DTStack/jlogstash-filter-plugin/issues

**Comment by walterxue** [comment]
好的！我來試試，有bug沒關係，我只是想要實際在生產環境上比較官方的logstash 跟 jlogstash 效能上的差異，很感謝你的回覆

**Comment by yangsishu** [comment]
bug 已经修复了，你可以拉下master 自己编译下 https://github.com/DTStack/jlogstash-filter-plugin

**Comment by walterxue** [comment]
好的!!
