### ISSUE TITLE
Cannot run program "gpg.exe": CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by xinzhuxiansheng** [DTStack/jlogstash#19]
单独打包 popeline下inputs 的file项目，出现 Cannot run program "gpg.exe": CreateProcess error=2, The system cannot find the file specified问题 ，这个是需要单独安装gpg.exe 再配置环境变量是么 ？ 
可否，方便有个开发环境搭建文档

**Comment by yangsishu** [comment]
去掉了gpg验证，你在试下

**Comment by xinzhuxiansheng** [comment]
你好 ，我启动 com.dtstack.jlogstash.JlogstashMain 的main 方法 ，可提示 找不到  java.lang.ClassNotFoundException: com.dtstack.jlogstash.inputs.File
疑问是： 这个类 是在 input.plugins项目中 ，可core项目中，没有依赖 这个项目，应该是找不到这个类。  我应该怎么做呢 ？ 

下面是我的配置文件:
inputs:
     - File:
         path:
           - D:\code\idea_workspace\github\jlogstash\yzhou_file.*\.txt$
         #heartbeatHost: 172.16.1.52:8854
         #userToken: kRhisbdoTQMCZU5KqQqGkQ7sDA7BM9kpldnQ5Nf2al8ER9yp
         #offsetDbSyncIntervalMs: 60000
         #heartbeatIntevalMs: 60000

outputs:
   - Performance:
        interval: 1
        path: D:/code/idea_workspace/github/jlogstash/yzhou_logs/beat-performance-%{+YYYY.MM.dd}.txt
        timeZone: Asia/Shanghai
        monitorPath: {"D:/code/idea_workspace/github/jlogstash/yzhou_logs/beat-performance-%{+YYYY.MM.dd}.txt":"8"}
   - Stdout:
        configs:
          codec: line

**Comment by yangsishu** [comment]
要是idea 本地debug，可以-dev这样的参数，如果是正式环境，要把插件包放到plugin目录下

**Comment by yangsishu** [comment]
github 上的wiki都有说明的

**Comment by xinzhuxiansheng** [comment]
谢谢了
