### ISSUE TITLE
fileter的grok正则解析如何配置

### ISSUE THREAD

**Issue by wangcegithub** [DTStack/jlogstash#25]

**Comment by yangsishu** [comment]
https://github.com/DTStack/jlogstash/tree/master/pipeline/filters

**Comment by wangcegithub** [comment]
patterns:必填 map结构，自定义的正则表达式，{"ip":"(?<fromApp>[0-9A-B])"} 如果:grok自带的已经有了,正则表达式不需要写，列如:{"%{COMBINEDAPACHELOG}":""}
我是按照这个配置的，是字段是前，还是正则在前啊，两种都是但是字段没有提取出来，用的是你的测试样例

**Comment by wangcegithub** [comment]
patterns:必填 map结构，
自定义的正则表达式，{"ip":"(?<fromApp>[0-9A-B])"} 
如果:grok自带的已经有了,正则表达式不需要写，列如:{"%{COMBINEDAPACHELOG}":""}
我是按照这个配置的，然后用了你的grok配置文件和日志样例，但是没有提取出字段
是字段在前边还是正则解析规则在前边啊

**Comment by wangcegithub** [comment]
或者能不能给一个正确的配置文件样例，貌似现在的文档和代码有些对不上

**Comment by wangcegithub** [comment]
配置文件如下：
inputs:
    - File:
        path:
          - /data/logs/aaa.log
filters:
    - JGrok:
        srcs: ["message"]
        patterns: {"%{COMBINEDAPACHELOG}":""}
#    - JGrok:
#        srcs: ["ip"]
#        patterns: {"ip":"(?<fromApp>[0-9A-B])"}
outputs:
    - Stdout:
        codec: java_lines
日志样例：
83.149.9.216 - - [17/Sep/2014:07:13:42 +0000] \"GET /presentations/logstash-monitorama-2013/images/kibana-search.png HTTP/1.1\" 200 203023 \"http://semicomplete.com/presentations/logstash-monitorama-2013/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.77 Safari/537.36\"

**Comment by wangcegithub** [comment]
配置样例如下：
inputs:
    - File:
        path:
          - /data/logs/aaa.log
filters:
    - JGrok:
        srcs: ["message"]
        patterns: {"%{COMBINEDAPACHELOG}":""}
outputs:
    - Stdout:
        codec: java_lines
日志样例：
83.149.9.216 - - [17/Sep/2014:07:13:42 +0000] \"GET /presentations/logstash-monitorama-2013/images/kibana-search.png HTTP/1.1\" 200 203023 \"http://semicomplete.com/presentations/logstash-monitorama-2013/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.77 Safari/537.36\"

输出结果：
{
"path" => "/data/logs/aaa.log",
"offset" => "996",
"message" => "83.149.9.216 - - [17/Sep/2014:07:13:42 +0000] \"GET /presentations/logstash-monitorama-2013/images/kibana-search.png HTTP/1.1\" 200 203023 \"http://semicomplete.com/presentations/logstash-monitorama-2013/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1700.77 Safari/537.36\"",
}

**Comment by wangcegithub** [comment]
ok
