### ISSUE TITLE
连接kafka10报错 jlogstash start error:null，启动不了

### ISSUE THREAD

**Issue by zt520374** [DTStack/jlogstash#34]
使用kafka10的inputs插件时，报以下error，启动失败。
2019-06-24 17:11:04.218 [main] WARN  com.dtstack.jlogstash.factory.InstanceFactory [InstanceFactory.java:64] - field: topics annotation:Required check
2019-06-24 17:11:04.221 [main] ERROR com.dtstack.jlogstash.JlogstashMain [JlogstashMain.java:53] - jlogstash start error:null
com.dtstack.jlogstash.annotation.plugin.RequiredPlugin.required(39)
com.dtstack.jlogstash.factory.InstanceFactory.checkAnnotation(139)
com.dtstack.jlogstash.factory.InstanceFactory.configInstance(65)
com.dtstack.jlogstash.factory.InputFactory.getInstance(44)
com.dtstack.jlogstash.factory.InputFactory.getBatchInstance(64)
com.dtstack.jlogstash.assembly.AssemblyPipeline.assemblyPipeline(96)
com.dtstack.jlogstash.JlogstashMain.main(51)

debug模式调试，定位代码com.dtstack.jlogstash.annotation.plugin.RequiredPlugin中required 为空指针。请看看是什么原因？
    public void required(Field field,Object obj) throws Exception{
        // TODO Auto-generated method stub
        Required required = field.getAnnotation(Required.class);
        if(required.required()&&obj==null){
            throw new RequiredException(field.getName());
        }

配置文件：
  inputs:
    - Kafka10:
        codec: json
        encoding: UTF8 # defaut UTF8
        topics: "my-slf4j-topic-test"
        groupId: "test"
        bootstrapServers: 172.18.231.8:32129,172.18.231.8:32130
        consumerSettings:
            auto.commit.interval.ms: "1000"
  outputs:
    - File:
        path: E:/dockerhub/jlogstash/srsyslog-performance-%{+YYYY.MM.dd}.txt

**Comment by yangsishu** [comment]
检查下required属性，有这个注解的属性是必填的

**Comment by zt520374** [comment]
恩。重新下载最新的更新编译后可以了。
