### ISSUE TITLE
请问如何过滤数据

### ISSUE THREAD

**Issue by liulongfei** [DTStack/jlogstash#5]
实现类似于下面的功能：

```
filter {
  if [loglevel] == "debug" {
    drop { }
  }
}
```
`Remove` 可以实现吗？如果可以，请帮忙写的例示。非常感谢！

**Comment by yangsishu** [comment]
过滤数据，需要自己写fliter插件,现在配置文件里不支持写过滤表达式

**Comment by yangsishu** [comment]
remove只能删除莫个属性

**Comment by yangsishu** [comment]
这个你得自己写个fliter插件，我们后续会支持配置文件里写groovy代码来实现简单的过滤表达式，你要是写filter插件有问题，可以直接来问我

**Comment by yangsishu** [comment]
插件样列开发 https://github.com/DTStack/jlogstash/tree/master/src/test/java/com/dtstack/jlogstash

**Comment by liulongfei** [comment]
DTStack 看着好熟悉。原来是刚向你们投的运维工程师简历。（逃
