### ISSUE TITLE
数据读取完成后不会自动退出虚拟机

### ISSUE THREAD

**Issue by zhangzhxb520** [DTStack/jlogstash#6]
看代码中使用的是阻塞队列，Input数据读取完后，OutputThread还被阻塞在，没办法自动退出虚拟机。

OutputThread中部分代码：　
                            if(!priorityFail()){
					event = this.outputQueue.take();
					if (event != null) {
						for (BaseOutput bo : outputProcessors) {
							bo.process(event);
						}
					}	
				}

**Comment by yangsishu** [comment]
这个是一个实时的应用 当然不会退出jv m
